version: '3'
services:
  hispana-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: website
    image: website
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    env_file:
      - .env.development

  hispana-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: hispana-prod
    ports:
      - '80:80'
    volumes:
      - '.:/app'
    env_file:
      - .env.production
